### ISSUE TITLE
🐞 Unhandled Exception: MissingPluginException. 

### ISSUE THREAD

**Issue by timrijckaert** [vrtdev/flutter_workmanager#6]
As discovered in #4.  
flutter_workmanager: `0.0.6+1`

It seems like it is currently impossible to use other plugins inside your background task as they are not registered.

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method FirebaseApp#appNamed on channel plugins.flutter.io/firebase_core)
```

Simple example:

pubspec:
```yaml
name: workmanager_example
description: Demonstrates how to use the workmanager plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  path_provider: ^1.2.0
  workmanager: 0.0.6+1
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

flutter:
  uses-material-design: true
```

main.dart
```dart
import 'dart:io';
import 'package:path_provider/path_provider.dart';
import 'dart:async';

import 'package:workmanager/workmanager.dart';

void callbackDispatcher() {
  Workmanager.defaultCallbackDispatcher((echoValue) async {
    switch (echoValue) {
      case simpleTaskKey:
        Directory tempDir = await getTemporaryDirectory();
        String tempPath = tempDir.path;
        break;
    }

    return Future.value(true);
  });
}
```
